/* QRImageBox.c generated by valac 0.36.14, the Vala compiler
 * generated from QRImageBox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "qrencode.h"
#include <librsvg/rsvg.h>


#define ELEMENTARY_QR_TYPE_QR_IMAGE_BOX (elementary_qr_qr_image_box_get_type ())
#define ELEMENTARY_QR_QR_IMAGE_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBox))
#define ELEMENTARY_QR_QR_IMAGE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBoxClass))
#define ELEMENTARY_QR_IS_QR_IMAGE_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX))
#define ELEMENTARY_QR_IS_QR_IMAGE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX))
#define ELEMENTARY_QR_QR_IMAGE_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBoxClass))

typedef struct _ElementaryQrQrImageBox ElementaryQrQrImageBox;
typedef struct _ElementaryQrQrImageBoxClass ElementaryQrQrImageBoxClass;
typedef struct _ElementaryQrQrImageBoxPrivate ElementaryQrQrImageBoxPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _QRcode_free0(var) ((var == NULL) ? NULL : (var = (QRcode_free (var), NULL)))

struct _ElementaryQrQrImageBox {
	GtkBox parent_instance;
	ElementaryQrQrImageBoxPrivate * priv;
};

struct _ElementaryQrQrImageBoxClass {
	GtkBoxClass parent_class;
};

struct _ElementaryQrQrImageBoxPrivate {
	GtkImage* qr_code_image;
	GtkButton* save_button;
	QRcode* _qrcode;
};


static gpointer elementary_qr_qr_image_box_parent_class = NULL;

GType elementary_qr_qr_image_box_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_QR_QR_IMAGE_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBoxPrivate))
enum  {
	ELEMENTARY_QR_QR_IMAGE_BOX_0_PROPERTY,
	ELEMENTARY_QR_QR_IMAGE_BOX_QRCODE_PROPERTY
};
ElementaryQrQrImageBox* elementary_qr_qr_image_box_new (void);
ElementaryQrQrImageBox* elementary_qr_qr_image_box_construct (GType object_type);
static void elementary_qr_qr_image_box_render (ElementaryQrQrImageBox* self);
QRcode* elementary_qr_qr_image_box_get_qrcode (ElementaryQrQrImageBox* self);
void elementary_qr_qr_image_box_set_qrcode (ElementaryQrQrImageBox* self, QRcode* value);
static void elementary_qr_qr_image_box_finalize (GObject * obj);
static void _vala_elementary_qr_qr_image_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_elementary_qr_qr_image_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


ElementaryQrQrImageBox* elementary_qr_qr_image_box_construct (GType object_type) {
	ElementaryQrQrImageBox * self = NULL;
	self = (ElementaryQrQrImageBox*) g_object_new (object_type, NULL);
	return self;
}


ElementaryQrQrImageBox* elementary_qr_qr_image_box_new (void) {
	return elementary_qr_qr_image_box_construct (ELEMENTARY_QR_TYPE_QR_IMAGE_BOX);
}


static void elementary_qr_qr_image_box_render (ElementaryQrQrImageBox* self) {
	RsvgHandle* rsvg = NULL;
	QRcode* _tmp0_;
	QRcode* _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	RsvgHandle* _tmp3_;
	GtkImage* _tmp4_;
	GdkPixbuf* _tmp5_;
	GdkPixbuf* _tmp6_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = elementary_qr_qr_image_box_get_qrcode (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_->data;
	_tmp2__length1 = -1;
	_tmp3_ = rsvg_handle_new_from_data (_tmp2_, _tmp2__length1, &_inner_error_);
	rsvg = _tmp3_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp4_ = self->priv->qr_code_image;
	_tmp5_ = rsvg_handle_get_pixbuf (rsvg);
	_tmp6_ = _tmp5_;
	g_object_set (_tmp4_, "pixbuf", _tmp6_, NULL);
	_g_object_unref0 (_tmp6_);
	_g_object_unref0 (rsvg);
}


QRcode* elementary_qr_qr_image_box_get_qrcode (ElementaryQrQrImageBox* self) {
	QRcode* result;
	QRcode* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_qrcode;
	result = _tmp0_;
	return result;
}


static gpointer _elementary_qr_qrcode_ref0 (gpointer self) {
	return self ? elementary_qr_qrcode_ref (self) : NULL;
}


void elementary_qr_qr_image_box_set_qrcode (ElementaryQrQrImageBox* self, QRcode* value) {
	QRcode* _tmp0_;
	QRcode* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _elementary_qr_qrcode_ref0 (_tmp0_);
	_QRcode_free0 (self->priv->_qrcode);
	self->priv->_qrcode = _tmp1_;
	elementary_qr_qr_image_box_render (self);
	g_object_notify ((GObject *) self, "qrcode");
}


static void elementary_qr_qr_image_box_class_init (ElementaryQrQrImageBoxClass * klass) {
	elementary_qr_qr_image_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ElementaryQrQrImageBoxPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_elementary_qr_qr_image_box_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_elementary_qr_qr_image_box_set_property;
	G_OBJECT_CLASS (klass)->finalize = elementary_qr_qr_image_box_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_QR_QR_IMAGE_BOX_QRCODE_PROPERTY, elementary_qr_param_spec_qrcode ("qrcode", "qrcode", "qrcode", ELEMENTARY_QR_TYPE_QRCODE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void elementary_qr_qr_image_box_instance_init (ElementaryQrQrImageBox * self) {
	self->priv = ELEMENTARY_QR_QR_IMAGE_BOX_GET_PRIVATE (self);
}


static void elementary_qr_qr_image_box_finalize (GObject * obj) {
	ElementaryQrQrImageBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBox);
	_g_object_unref0 (self->priv->qr_code_image);
	_g_object_unref0 (self->priv->save_button);
	_QRcode_free0 (self->priv->_qrcode);
	G_OBJECT_CLASS (elementary_qr_qr_image_box_parent_class)->finalize (obj);
}


GType elementary_qr_qr_image_box_get_type (void) {
	static volatile gsize elementary_qr_qr_image_box_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_qr_qr_image_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryQrQrImageBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_qr_qr_image_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryQrQrImageBox), 0, (GInstanceInitFunc) elementary_qr_qr_image_box_instance_init, NULL };
		GType elementary_qr_qr_image_box_type_id;
		elementary_qr_qr_image_box_type_id = g_type_register_static (gtk_box_get_type (), "ElementaryQrQrImageBox", &g_define_type_info, 0);
		g_once_init_leave (&elementary_qr_qr_image_box_type_id__volatile, elementary_qr_qr_image_box_type_id);
	}
	return elementary_qr_qr_image_box_type_id__volatile;
}


static void _vala_elementary_qr_qr_image_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ElementaryQrQrImageBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBox);
	switch (property_id) {
		case ELEMENTARY_QR_QR_IMAGE_BOX_QRCODE_PROPERTY:
		elementary_qr_value_set_qrcode (value, elementary_qr_qr_image_box_get_qrcode (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_elementary_qr_qr_image_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ElementaryQrQrImageBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEMENTARY_QR_TYPE_QR_IMAGE_BOX, ElementaryQrQrImageBox);
	switch (property_id) {
		case ELEMENTARY_QR_QR_IMAGE_BOX_QRCODE_PROPERTY:
		elementary_qr_qr_image_box_set_qrcode (self, elementary_qr_value_get_qrcode (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



